export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_NESTED_LINK_1 = "SET_NESTED_LINK_1";
export const SET_NESTED_LINK_2 = "SET_NESTED_LINK_2";
export const SET_NESTED_LINK_3 = "SET_NESTED_LINK_3";
export const SET_NESTED_LINK_4 = "SET_NESTED_LINK_4";
export const SET_NESTED_LINK_5 = "SET_NESTED_LINK_5";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const GET_USER_PERMISSIONS = "GET_USER_PERMISSIONS";
export const GET_USER_PERMISSIONS_SUCCESS = "GET_USER_PERMISSIONS_SUCCESS";
export const GET_USER_PERMISSIONS_FAILURE = "GET_USER_PERMISSIONS_FAILURE";

export const LOG_OUT = "LOG_OUT"


